#
# B+
#
# Copyright (C) 2017 Jorge Vieira, José Sousa, Miguel Reboiro-Jato,
# Noé Vázquez, Bárbara Amorim, Cristina P. Vieira, André Torres, Hugo
# López-Fernández, and Florentino Fdez-Riverola
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

version: '3.4'
services:
  database:
    build:
      context: ..
      dockerfile: docker/Dockerfile.database
    container_name: bpositive-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "bpositivepass"
      MYSQL_DATABASE: "bpositive"
      MYSQL_USER: "bpositive"
      MYSQL_PASSWORD: "bpositivepass"
    volumes:
      - bpositive-database-data:/var/lib/mysql
    networks:
      bpositive-network:
        ipv4_address: 172.20.1.10
    command: --wait_timeout=28800
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: bpositive-backend
    ports:
      - "80:80"
    restart: always
    privileged: true
    depends_on:
      - database
    volumes:
      - ./backend:/var/www/html
    networks:
      bpositive-network:
        ipv4_address: 172.20.1.20
volumes:
  bpositive-database-data:
networks:
  bpositive-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.1.0/16
